name: Package with Pyinstaller

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
    branches:
      - master

jobs:
  package:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ 'ubuntu-20.04', 'windows-latest', 'macos-11' ]
        python-version: [ 3.11 ]

    steps:
      - uses: &checkout_action actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Package for ${{ matrix.os }}
        run: python dist.py
      - name: Add generated binary to artifact
        uses: &upload_artifact_action actions/upload-artifact@v3
        with: &upload_artifact_args
          name: &artifact_name nexus-build
          path: |
            ./dist/nexus
            ./dist/nexus-macos
            ./dist/nexus.exe
          if-no-files-found: error
        if: always()

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: *checkout_action
      - name: Add README.md and LICENSE to artifact
        uses: *upload_artifact_action
        with:
          <<: *upload_artifact_args
          path: |
            LICENSE
            README.md

  release:
    needs: [ package, docs ]
    runs-on: ubuntu-latest
    if: |
      github.repository_owner == 'CharaChorder' &&
      github.event_name != 'pull_request'
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: *artifact_name
      - uses: pyTooling/Actions/releaser@r0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            nexus
            nexus.exe
            nexus-macos
            README.md
            LICENSE
